# Generated by Django 3.2.4 on 2021-07-01 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210701_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 21, 15, 3, 481774)),
        ),
    ]
